name: detect merge
on:
  pull_request_target:
    types: ['opened', 'synchronize']
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
jobs:
  detect-mergeability:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo '${{ toJson(github.event) }}'
    # - name: Notify workflow failure if PR is not mergeable
    #   if: github.event.pull_request.mergeable != true
    #   uses: actions/github-script@v3
    #   with: 
    #     script: |
    #         github.issues.createComment({
    #           issue_number: context.issue.number,
    #           owner: context.repo.owner,
    #           repo: context.repo.repo,
    #           body: '[SET-BUILD-ENVIRONMENT]: Unable to detect build environment as PR is not mergeable (most probably contains merge conflicts). Fix merge conflicts in the source branch and push to rerun the workflow.'
    #         })
