name: detect-mergeability
on:
  pull_request_target:
    types: ['opened', 'synchronize']
permissions:
  issues: write
  pull-requests: write
    
jobs:
  detect-mergeability:
    runs-on: ubuntu-latest
    steps:
    - name: Sleep to ensure we detect mergeability
      run: |
        sleep 120
    - name: Notify workflow failure if PR is not mergeable
      if: ${{ ! github.event.pull_request.mergeable == true && ! github.event.pull_request.mergeable == null }}
      uses: actions/github-script@v3
      with: 
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '[SET-BUILD-ENVIRONMENT]: Unable to detect build environment as PR is not mergeable (most probably contains merge conflicts). Fix merge conflicts in the source branch and push to rerun the workflow.'
            })
