name: Build on OpenWRT Image Builder
on: 
  push:
    branches: [ 'main' ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: checks docker presence
        run: |
          docker ps
