name: Get Comment Details
on:
  issue_comment:
    types: [created, edited]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Run on specific comment
          if: contains(${{ github.event.comment.body }}, 'hello')
          run: echo ${{ github.event.comment.body }}
