name: Set Environment
on:
  pull_request_target:
    types: ['opened', 'synchronize']
    branches: ['main']
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
  ENV_FILE_PATH: build_env
    
jobs:
  set-environment:
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'
    steps:
    - name: Set environment to local variable
      id: set-build-env
      run: |
        echo "BUILD_ENV=PRODUCTION" >> $GITHUB_OUTPUT
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Create environment file
      id: create-env-file
      continue-on-error: true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'

        echo -n "${{ steps.set-build-env.outputs.BUILD_ENV }}" > $ENV_FILE_PATH

        git add -A
        if git diff --staged --quiet $ENV_FILE_PATH; then
          exit 2
        fi
        
        git commit -m "[set-build-env] include build env"
        git push
    - name: Comment successful build environment addition
      if: steps.create-env-file.outcome != 'failure'
      uses: actions/github-script@v3
      with: 
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Detected build environment '${{ steps.set-build-env.outputs.BUILD_ENV }}' written to build_env file on branch '${{ github.event.pull_request.base.ref }}'. Do not overwrite this file."
            })
