name: Set Environment
on:
  pull_request:
    types: ['opened', 'synchronize']
permissions:
  contents: write
  pull-requests: write
env:
  GH_TOKEN: ${{ github.token }}
  ENV_FILE_PATH: build_env
    
jobs:
  set-environment:
    runs-on: ubuntu-latest
    steps:
    - name: Set environment to local variable
      id: set-build-env
      run: |
        if [[ ${{ github.base_ref == 'main' }} ]]; then
          echo "BUILD_ENV=PRODUCTION" >> $GITHUB_OUTPUT
        else
          echo "BUILD_ENV=DEVELOPMENT" >> $GITHUB_OUTPUT
        fi
    - name: checkout repository
      uses: actions/checkout@v4
    - name: Create environment file
      id: create-env-file
      continue-on-error: true
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        gh pr checkout ${{ github.event.pull_request.number }}
        echo -n "${{ steps.set-build-env.outputs.BUILD_ENV }}" > $ENV_FILE_PATH
        if [[ $(git diff --quiet --exit-code $ENV_FILE_PATH) -eq 0 ]]; then
          exit 1
        fi  
        git add -A
        git commit -m "[set-build-env] include build env"
        git push
    - name: Comment successful build environment addition
      if: steps.create-env-file.conclusion != 'failure'
      uses: actions/github-script@v3
      with: 
        script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Detected build environment '${{ steps.set-build-env.outputs.BUILD_ENV }}' written to build_env file. Do not overwrite this file."
            })
