name: Set Version
on: [issue_comment]

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/set-version"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        id: prcomm
      - uses: actions/checkout@v4
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
      - name: Echo Version Number to PR
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        run: |
          echo "ref:${{ steps.prcomm.outputs.BRANCH_NAME }}"
          echo "headref:${{ github.head_ref }}"
          echo "version=${{ steps.prcomm.outputs.TRAILING_TOKEN }}" > version.txt
      - name: Commit changes to the PR branch
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        run: |
          git config --global user.name 'actions-bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          git checkout -b gha-versioning-branch
          git add version.txt
          git commit -m "[fix-pr-command] fixes"
          git push origin gha-versioning-branch:${{ steps.prcomm.outputs.BRANCH_NAME }}
