name: Set Version
on: [issue_comment]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  process-set-version:
    runs-on: ubuntu-latest
    steps:
      - name: listen for PR Comments
        id: prcomm
        uses: machine-learning-apps/actions-chatops@master
        with:
          TRIGGER_PHRASE: "/set-version"
      - name: checkout repository
        if: steps.prcomm.outputs.BOOL_TRIGGERED == 'true'
        uses: actions/checkout@v4
      - name: add versioning
        run: |
          git config --global user.name 'actions-bot'
          git config --global user.email 'actions-bot@users.noreply.github.com'
          gh pr checkout ${{ steps.prcomm.outputs.PULL_REQUEST_NUMBER }}
          echo "version=${{ steps.prcomm.outputs.TRAILING_TOKEN }}" > version
          git add -A
          git commit -m "[set-version-command] include version file"
          git push
